apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: iliketrains-info-tls
spec:
  secretName: iliketrains-info
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: iliketrains.info
  dnsNames:
    - iliketrains.info
    - www.iliketrains.info
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - iliketrains.info
          - www.iliketrains.info